// Copyright (c) The Lambdanio Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit.

#ifndef LAMBDANIO_CHAINPARAMSSEEDS_H
#define LAMBDANIO_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the lambdanio network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
};
#endif // LAMBDANIO_CHAINPARAMSSEEDS_H
